language: node_js
node_js: 
 - "12"
jdk:
 - oraclejdk8
addons:
 sonarcloud: true 
script:
 - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=royk8 -Dsonar.projectKey=lab2arquisoft -Dsonar.sources='./app' -X

